DROP TABLE HISTCOMPRAS CASCADE CONSTRAINTS;

CREATE TABLE HISTCOMPRAS
(
  CPF                   NUMBER(14)      PRIMARY KEY NOT NULL,         
  PRIVATEX              NUMBER(1)       NOT NULL,
  INCOMPLETO            NUMBER(1)       NOT NULL,
  DT_ULT_COMPRA         DATE,            
  TICKET_MÉDIO          NUMBER(12,2),
  TICKET_ULT_COMPRA     NUMBER(12,2),
  LOJA_MAIS_FREQ        NUMBER(14),
  LOJA_ULT_COMPRA       NUMBER(14),
  CPF_VALIDO            CHAR(1),
  CNJP_FREQ_VALIDO      CHAR(1),
  CNJP_ULT_VALIDO       CHAR(1),
  DT_ATUALIZACAO        DATE  
);  
